branches:
  - master

deploy:
  rsync:
    user: $$DEPLOY_USER
    host: docs.aplazame.com
    target: $$RELEASE_PATH
    delete: false
    recursive: true
    commands:
      - 'source ~/.zshrc'
      - 'cd $$RELEASE_PATH'
      - 'rake'

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: 'drone'
    channel: 'developers'
    when:
      success: false
      failure: true
      change: true

  email:
    from: $$EMAIL_FROM
    host: $$EMAIL_HOST
    username: $$EMAIL_USERNAME
    password: $$EMAIL_PASS
    recipients:
      - dev@aplazame.com
    when:
      success: false
      failure: true
      change: true
